### ISSUE TITLE
Support for papers not on arXiv

### ISSUE THREAD

**Issue by trane293** [ShortScience-org/shortscience.org#20]
Hello!

I was recently trying to upload a summary of a paper that was not on arXiv. It was recently published with a valid DOI, but the search functionality on shortscience was still not able to find it (it returns results only on arXiv). Is there support for papers that are not uploaded to arXiv (for papers coming from medical community on the intersection of computer science/ML and medical imaging)?

**Comment by trane293** [comment]
The paper in question is - http://clincancerres.aacrjournals.org/content/early/2018/05/22/1078-0432.CCR-17-3445

The DOI is: 10.1158/1078-0432.CCR-17-3445

**Comment by ieee8023** [comment]
Sorry for the very late reply. This was an issue in how we parsed DOIs containing dashes. The search is fixed and you can find the paper using the search:

http://www.shortscience.org/search?term=10.1158%2F1078-0432.CCR-17-3445

We support much more than ArXiv. There are three main databases: DOIs, Bibsonomy (everything before DOIs), and ArXiv.
