### ISSUE TITLE
Add option to edit summaries

### ISSUE THREAD

**Issue by fabioperez** [ShortScience-org/shortscience.org#21]
It would be interesting to have some option to edit our own summaries. Also, a wiki-style editing also seems interesting. It looks better than having multiple summaries, IMO.

**Comment by ieee8023** [comment]
You can edit your own summary. Just scroll down to the bottom. I will add something to make this more clear.

We believe summary ownership is important so each person has their own text that they control. This way your name and image are next to your summary and you can use your summary to promote yourself and establish yourself as a knowledge leader.

**Comment by ieee8023** [comment]
A button has been added to make editing easier. Let me know if you think we should do something else.
