### ISSUE TITLE
A redesign?

### ISSUE THREAD

**Issue by chsasank** [ShortScience-org/shortscience.org#4]
Hi,

Would you be interested in (frontend) redesign of the site? I can do it in my free time. 

I'm inspired by design of stackoverflow. Here is a simple prototype I've come up with.

![screen shot 2017-06-22 at 11 20 56 am](https://user-images.githubusercontent.com/9305875/27419137-f20081fa-573c-11e7-8618-2c0e9b9ac938.png)

Sasank.

**Comment by ieee8023** [comment]
Thanks!

Can you supply CSS? Maybe we can add a theme option where we just include custom CSS?

**Comment by chsasank** [comment]
Obviously, the [ html from screenshot](https://github.com/ieee8023/shortscience.org/files/1095663/strap.html.zip) is very limited. 

You can see that menu to share etc are below the summary. I'll add the author info next to the menu like in stackoverflow. It's not a simple CSS change, rather an html redesign.

Sasank.
